const assert=require('node:assert/strict');
const P=require('../web/presentation.js');
const row=(id,status,size,extra={})=>({world_id:id,status,deleted:true,error:null,factors:{node:'26.8.1',size,width:32,length:'implicit',allocation:'pooled',...extra}});
const fail=row('fail-001','FAIL',10), pass=row('pass-002','PASS',20);
assert.equal(P.contrast([fail,pass]).factor,'size');
assert.equal(P.contrast([fail,row('other','PASS',20,{width:8})]),null);
assert.equal(P.contrast([fail,{...pass,deleted:false}]),null);
const action={action:'SEARCH_BOUNDARY',factor:'size',fixed:{node:'26.8.1',width:32,length:'implicit',allocation:'pooled'},reason:'fail-001 FAIL; pass-002 PASS'};
const event=(event,data)=>({event,data});
assert.ok(P.decision([event('observations',{observations:[fail,pass]}),event('action',action)]).pair);
assert.equal(P.decision([event('observations',{observations:[fail]}),event('action',action),event('observations',{observations:[pass]})]).pair,null);
assert.equal(P.decision([event('observations',{observations:[fail,pass]}),event('action',{...action,reason:'fail-0010 FAIL; pass-002 PASS'})]).pair,null);
assert.equal(P.decision([event('observations',{observations:[row('early','FAIL',1),fail,pass]}),event('action',{...action,values:{min:10,max:20,seed_observed_bad:10},reason:'early FAIL, fail-001 FAIL and pass-002 PASS'})]).pair.fail.factors.size,10);
const raw=({factors,...o})=>o;
const wire=[event('worlds_submitted',{worlds:[fail,pass].map(o=>({world_id:o.world_id,factor_values:o.factors}))}),...[fail,pass].map(o=>event('world_completed',{observation:raw(o),valid:true})),event('observations',{observations:[raw(fail),raw(pass)]}),event('action',action)];
assert.equal(P.decision(wire).pair.factor,'size');
assert.equal(P.decision(wire.filter(e=>e.event!=='world_completed')).pair,null);
assert.match(P.lifecycle({phases:['CREATED','DESTROYED']},'daytona'),/EXECUTED pending/);
assert.match(P.lifecycle({observation:{deleted:true}},'local'),/NOT A SANDBOX/);
assert.equal(P.eligible({summary:{backend:'local',planner:'openai',status:'VERIFIED_FAILURE_CONDITION'}}),false);
const observations=Array.from({length:10},(_,i)=>row('confirm-'+i,i<5?'FAIL':'PASS',i<5?10:11));
const good={active:false,summary:{backend:'daytona',planner:'openai',status:'VERIFIED_FAILURE_CONDITION',planner_closed_loop:true,worlds_submitted:10,actions:[{action:'STOP'}],observations,boundary:{factor:'size',fail:10,pass:11,fixed:action.fixed,confirmation_world_ids:observations.map(o=>o.world_id)}},events:observations.flatMap(o=>['CREATED','DESTROYED'].map(phase=>event('world_phase',{world_id:o.world_id,sandbox_id:o.world_id,phase})))};
assert.equal(P.eligible(good),true);
assert.equal(P.eligible({...good,active:true}),false);
assert.equal(P.eligible({...good,summary:{...good.summary,status:'CANCELLED'}}),false);
assert.equal(P.eligible({...good,events:good.events.slice(0,-1)}),false);
assert.equal(P.eligible({...good,summary:{...good.summary,planner:'rules'}}),false);
assert.equal(P.eligible({...good,summary:{...good.summary,planner_closed_loop:false}}),false);
console.log('Presentation assertions passed: contrasts, chronological evidence, search seed, lifecycle, demo eligibility.');
